name: Trigger Pipeline on Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Git content to a folder
        run: |
          git pull
          git pull origin develop:/var/lib/jenkins/gitpull
